services:
  api:
    env_file:
      - "auctionhouse/.env"
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/auctionhouse/api:v${VERSION}
    #TODO: change ports to expose when going into prod and using an apiserver to manage incoming
    ports:
      - "1280:9100"
    restart: always
    volumes:
      - ${LOCAL_LOG_LOC}:${LOGFILE_VOL}
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - poptape
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${AUCTIONHOUSE_DB_PASS}
      - POSTGRES_USER=${AUCTIONHOUSE_DB_USER}
      - POSTGRES_DB=${AUCTIONHOUSE_DB_NAME}
    ports:
      - "1281:5432"
    expose:
      - "5432"
    volumes:
      - poptape_auctionhouse_data:/var/lib/postgresql/data
    networks:
      - poptape
networks:
  poptape:
    external: true
volumes:
  poptape_auctionhouse_data:
    name: poptape_auctionhouse_data
  
