# Generated by Django 2.2.2 on 2019-06-21 16:03

import auctionhouse.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_id',
            field=models.CharField(max_length=36, unique=True, validators=[auctionhouse.validators.validate_uuid_from_model]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='owner',
            field=models.CharField(max_length=36, validators=[auctionhouse.validators.validate_uuid_from_model]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='type',
            field=models.CharField(choices=[('EN', 'English'), ('DU', 'Dutch'), ('SB', 'Sealed Bid'), ('VK', 'Vickery'), ('RV', 'Reverse'), ('BF', 'Bidding Fee'), ('BN', 'Buy Now'), ('MO', 'Make Me An Offer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='item_id',
            field=models.CharField(max_length=36, unique=True, validators=[auctionhouse.validators.validate_uuid_from_model]),
        ),
    ]
