# Generated by Django 2.2.2 on 2019-07-09 13:41

import auctionhouse.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='lot_id',
            field=models.CharField(default=2, max_length=36, unique=True, validators=[auctionhouse.validators.validate_uuid_from_model]),
            preserve_default=False,
        ),
    ]
