# Generated by Django 2.2.2 on 2019-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20190710_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlot',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
