# Generated by Django 2.2.2 on 2019-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20190710_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlot',
            name='current_bid_currency',
        ),
        migrations.RemoveField(
            model_name='auctionlot',
            name='starting_bid_currency',
        ),
        migrations.RemoveField(
            model_name='auctionlot',
            name='winning_bid_currency',
        ),
        migrations.RemoveField(
            model_name='buynowauctionlot',
            name='buy_now_price_currency',
        ),
        migrations.RemoveField(
            model_name='englishauctionlot',
            name='min_increment_currency',
        ),
        migrations.RemoveField(
            model_name='englishauctionlot',
            name='reserve_price_currency',
        ),
        migrations.RemoveField(
            model_name='englishauctionlot',
            name='start_price_currency',
        ),
        migrations.AddField(
            model_name='auction',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='current_bid',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='starting_bid',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='winning_bid',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='buynowauctionlot',
            name='buy_now_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='englishauctionlot',
            name='min_increment',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='englishauctionlot',
            name='reserve_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='englishauctionlot',
            name='start_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
