# Generated by Django 2.2.4 on 2019-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20190710_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
