# Generated by Django 2.2.4 on 2019-10-05 16:07

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20191005_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlot',
            name='start_time',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True),
        ),
    ]
