# Generated by Django 2.2.4 on 2019-10-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auto_20191008_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='no_of_bids',
            field=models.IntegerField(default=0),
        ),
    ]
