# Generated by Django 2.2.4 on 2019-10-13 09:20

import auctionhouse.validators
from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_auctionlot_no_of_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.CharField(max_length=36, unique=True, validators=[auctionhouse.validators.validate_uuid_from_model])),
                ('username', models.CharField(max_length=36)),
                ('your_bid', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, validators=[auctionhouse.validators.validate_decimals])),
                ('current_winning_bid', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, validators=[auctionhouse.validators.validate_decimals])),
                ('current_winning_bid_id', models.CharField(max_length=36, validators=[auctionhouse.validators.validate_uuid_from_model])),
                ('bid_status', models.CharField(max_length=10)),
                ('lot_status', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=50)),
                ('unixtime', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot', to='auction.AuctionLot')),
            ],
        ),
    ]
