# Generated by Django 2.2.4 on 2019-10-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_bidhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlot',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='auctionlot',
            name='no_of_bids',
        ),
        migrations.RemoveField(
            model_name='auctionlot',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='auctionlot',
            name='winning_bid',
        ),
    ]
