# Generated by Django 2.2.4 on 2019-10-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_auctionlot_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlot',
            name='auction',
        ),
    ]
