# Generated by Django 2.2.4 on 2019-10-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_auctionlot_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlot',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='bidhistory',
            name='lot',
        ),
    ]
