# Generated by Django 2.2.4 on 2019-10-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0022_auto_20191014_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhistory',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lot', to='auction.AuctionLot'),
            preserve_default=False,
        ),
    ]
