# Generated by Django 2.2.4 on 2019-10-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0024_auto_20191014_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidhistory',
            name='unixtime',
            field=models.BigIntegerField(),
        ),
    ]
