# Generated by Django 2.2.4 on 2019-10-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0025_auto_20191014_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidhistory',
            name='current_winning_bid',
        ),
        migrations.RemoveField(
            model_name='bidhistory',
            name='current_winning_bid_id',
        ),
    ]
