# Generated by Django 2.2.4 on 2019-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0027_auto_20191015_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynowauctionlot',
            name='make_an_offer',
            field=models.BooleanField(default=False),
        ),
    ]
