# Generated by Django 2.2.4 on 2019-10-22 15:24

import auctionhouse.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0028_buynowauctionlot_make_an_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_transfer', models.BooleanField(default=False)),
                ('mastercard', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('amex', models.BooleanField(default=False)),
                ('bitcoin', models.BooleanField(default=False)),
                ('paypal', models.BooleanField(default=False)),
                ('venmo', models.BooleanField(default=False)),
                ('cash', models.BooleanField(default=False)),
                ('cheque', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auction.Auction')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postage', models.BooleanField(default=False)),
                ('postage_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[auctionhouse.validators.validate_decimals])),
                ('collection', models.BooleanField(default=False)),
                ('collection_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[auctionhouse.validators.validate_decimals])),
                ('delivery', models.BooleanField(default=False)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[auctionhouse.validators.validate_decimals])),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='auction.AuctionLot')),
            ],
        ),
    ]
