# Generated by Django 2.2.4 on 2019-10-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0029_deliveryoptions_paymentoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoptions',
            name='lot',
        ),
        migrations.AddField(
            model_name='deliveryoptions',
            name='lot_id',
            field=models.CharField(default='dfdfdf', max_length=36),
            preserve_default=False,
        ),
    ]
