# Generated by Django 2.2.4 on 2019-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0030_auto_20191022_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentoptions',
            name='auction',
        ),
        migrations.AddField(
            model_name='paymentoptions',
            name='auction_id',
            field=models.CharField(default='blah', max_length=36),
            preserve_default=False,
        ),
    ]
