# Generated by Django 2.2.4 on 2019-10-28 12:00

import auctionhouse.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0031_auto_20191022_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhistory',
            name='public_id',
            field=models.CharField(default='f38ba39a-3682-4803-a498-659f0bf05304', max_length=36, validators=[auctionhouse.validators.validate_uuid_from_model]),
            preserve_default=False,
        ),
    ]
