# Generated by Django 4.2.7 on 2023-11-14 22:06

import auctionhouse.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0033_auto_20191028_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='auctionlot',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bidhistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, validators=[auctionhouse.validators.validate_uuid_from_model]),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='lot_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, validators=[auctionhouse.validators.validate_uuid_from_model]),
        ),
        migrations.AlterField(
            model_name='bidhistory',
            name='bid_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, validators=[auctionhouse.validators.validate_uuid_from_model]),
        ),
    ]
